sonar.projectKey=spendsmart
sonar.projectName=SpendSmart
sonar.projectVersion=0.1.0

sonar.sources=services
sonar.tests=tests
sonar.test.inclusions=**/*.test.js

sonar.language=js
sonar.scm.provider=git
sonar.sourceEncoding=UTF-8

# Cobertura (lcov gerado pelo Jest)
sonar.javascript.lcov.reportPaths=coverage/lcov.info
